### ISSUE TITLE
Any Kubernetes Statefulset YAML ready for a cluster with pg_auto_failover ? 

### ISSUE THREAD

**Issue by nijesh8** [hapostgres/pg_auto_failover#1001]
Any Kubernetes Statefulset YAML ready for a cluster with pg_auto_failover ? 
If you have one, could you share. 

We are using Kubernetes environments and migrating Oracle databases to Postgresql on Kubernetes pods. 
We are evaluating HA solutions for Postgres, (example Patroni or pg_auto_failover).

Please advise. 

Thanks, 
Nijesh

**Comment by dimitri** [comment]
What would be needed here is a Kubenetes operator for pg_auto_failover. The operator would then instruct you how to setup your nodes and provide YAML snippets for you to setup. I don't think that such a Kubernetes operator is in the works at the moment.
