### ISSUE TITLE
Minimal supported postgresql version

### ISSUE THREAD

**Issue by nnovikov** [hapostgres/pg_auto_failover#1034]
Hello!
I did not find this question in the documentation. What is the minimum version of the postgresql database supported by pg_auto_failover? Can I use it with postgresql 9.6 for example?

**Comment by hashworks** [comment]
pgsql v9 is not supported. See the Makefile, [line 7 says v11-16](https://github.com/hapostgres/pg_auto_failover/blob/v2.1/Makefile#L7).

**Comment by nnovikov** [comment]
Many thanks!
