### ISSUE TITLE
How to install v2.0 with CentOS7 using yum?

### ISSUE THREAD

**Issue by z3473** [hapostgres/pg_auto_failover#998]

**Comment by xinferum** [comment]
Hello.

You can add vanilla official PostgreSQL repo to your system from this page https://www.postgresql.org/download/linux/redhat/ :
```
# Install the repository RPM:
sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
```

And install pg_auto_failover using yum for your major PostgreSQL version:
```
# Example for PostgreSQL 15
pg_auto_failover-15
```
